name: Screenshot and tweet

# on:
#   schedule:
#     - cron: "0 * * * *"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: Iamshankhadeep/setup-ffmpeg@v1.2
        with:
          # Not strictly necessary, but it may prevent rate limit
          # errors especially on GitHub-hosted macos machines.
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: yarn install
      - name: Create env file
        run: |
          touch .env
          echo SUPABASE_URL=${{ secrets.SUPABASE_URL }} >> .env
          echo SUPABASE_TOKEN=${{ secrets.SUPABASE_TOKEN }} >> .env
          echo TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }} >> .env
          echo TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} >> .env
          echo TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }} >> .env
          echo TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }} >> .env
          cat .env
      - name: Run script
        run: yarn start
    timeout-minutes: 7